### ISSUE TITLE
I would like help if you want

### ISSUE THREAD

**Issue by LeandroFonseca02** [metzlr/portals#1]
Im doing a university project and im doing a puzzle game. I saw your portals and would like to use it if you authorize me of course, but im be trying to setup your live demo but i cannot. Can you help to setup?
Im trying to make a portal class to make an easier usage of Portal's in Threejs but im struggling with some methods you have on SceneManager related to rendering portals.
Thanks in advance

**Comment by LeandroFonseca02** [comment]
Im trying to reuse your code to an easier usage. Just like instanciate a Portals class and add it to the scene but im struggling with your SceneManager methods referenced to portals rendering.
Thanks!

**Comment by metzlr** [comment]
Yeah I've been meaning to make the portals easier to use for awhile. The recent changes I made hopefully improve things. Take a look at the [README](https://github.com/metzlr/portals/blob/main/README.md) for a brief overview of how things work now and check out the [PortalSceneManager](https://github.com/metzlr/portals/blob/main/demo/js/objects/PortalSceneManager.js) class as an example.

**Comment by LeandroFonseca02** [comment]
Thanks Im being trying to understand and I make it to work but your changes are awesome! 
Thanks for being gentle!

**Comment by LeandroFonseca02** [comment]
Hi there did you know how to create some type of player collision, I see you have something of that on your demo but I'm searching on Internet about threejs player physics and i'm not getting it. Im trying to make a plataform game.
Thanks in advance
